// Code generated by mockery v1.0.0. DO NOT EDIT.

package securitymock

import (
	context "context"

	model "github.com/slok/bilrost/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AuthBackendRepository is an autogenerated mock type for the AuthBackendRepository type
type AuthBackendRepository struct {
	mock.Mock
}

// GetAuthBackend provides a mock function with given fields: ctx, id
func (_m *AuthBackendRepository) GetAuthBackend(ctx context.Context, id string) (*model.AuthBackend, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.AuthBackend
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AuthBackend); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthBackend)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
