// Code generated by mockery v1.0.0. DO NOT EDIT.

package authbackendmock

import (
	authbackend "github.com/slok/bilrost/internal/authbackend"
	mock "github.com/stretchr/testify/mock"

	model "github.com/slok/bilrost/internal/model"
)

// AppRegistererFactory is an autogenerated mock type for the AppRegistererFactory type
type AppRegistererFactory struct {
	mock.Mock
}

// GetAppRegisterer provides a mock function with given fields: ab
func (_m *AppRegistererFactory) GetAppRegisterer(ab model.AuthBackend) (authbackend.AppRegisterer, error) {
	ret := _m.Called(ab)

	var r0 authbackend.AppRegisterer
	if rf, ok := ret.Get(0).(func(model.AuthBackend) authbackend.AppRegisterer); ok {
		r0 = rf(ab)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authbackend.AppRegisterer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.AuthBackend) error); ok {
		r1 = rf(ab)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
