// Code generated by mockery v1.0.0. DO NOT EDIT.

package authbackendmock

import authbackend "github.com/slok/bilrost/internal/authbackend"
import context "context"
import mock "github.com/stretchr/testify/mock"

// AppRegisterer is an autogenerated mock type for the AppRegisterer type
type AppRegisterer struct {
	mock.Mock
}

// RegisterApp provides a mock function with given fields: ctx, app
func (_m *AppRegisterer) RegisterApp(ctx context.Context, app authbackend.OIDCApp) error {
	ret := _m.Called(ctx, app)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, authbackend.OIDCApp) error); ok {
		r0 = rf(ctx, app)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnregisterApp provides a mock function with given fields: ctx, appID
func (_m *AppRegisterer) UnregisterApp(ctx context.Context, appID string) error {
	ret := _m.Called(ctx, appID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, appID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
