// Code generated by mockery v1.0.0. DO NOT EDIT.

package proxymock

import context "context"
import mock "github.com/stretchr/testify/mock"
import proxy "github.com/slok/bilrost/internal/proxy"

// OIDCProvisioner is an autogenerated mock type for the OIDCProvisioner type
type OIDCProvisioner struct {
	mock.Mock
}

// Provision provides a mock function with given fields: ctx, settings
func (_m *OIDCProvisioner) Provision(ctx context.Context, settings proxy.OIDCProxySettings) error {
	ret := _m.Called(ctx, settings)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.OIDCProxySettings) error); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unprovision provides a mock function with given fields: ctx, settings
func (_m *OIDCProvisioner) Unprovision(ctx context.Context, settings proxy.OIDCProxySettings) error {
	ret := _m.Called(ctx, settings)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.OIDCProxySettings) error); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
