// Code generated by mockery v1.0.0. DO NOT EDIT.

package oauth2proxymock

import context "context"
import corev1 "k8s.io/api/core/v1"
import mock "github.com/stretchr/testify/mock"

import v1 "k8s.io/api/apps/v1"

// KubernetesRepository is an autogenerated mock type for the KubernetesRepository type
type KubernetesRepository struct {
	mock.Mock
}

// EnsureDeployment provides a mock function with given fields: ctx, dep
func (_m *KubernetesRepository) EnsureDeployment(ctx context.Context, dep *v1.Deployment) error {
	ret := _m.Called(ctx, dep)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Deployment) error); ok {
		r0 = rf(ctx, dep)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureService provides a mock function with given fields: ctx, svc
func (_m *KubernetesRepository) EnsureService(ctx context.Context, svc *corev1.Service) error {
	ret := _m.Called(ctx, svc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Service) error); ok {
		r0 = rf(ctx, svc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
